name: Build and test

on:
  push:
    branches: [ main ]
    tags: ['*']
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build app for release
        run: msbuild cewrapper.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release -property:Platform=x64

      - uses: actions/upload-artifact@v4
        with:
          name: cewrapper
          path: D:\a\cewrapper\cewrapper\x64\Release\cewrapper.exe 

  deploy:
    needs: [build]
    runs-on: ubuntu-20.04

    steps:
      - name: Download the built distribution
        uses: actions/download-artifact@v4
        with:
          name: cewrapper
          path: cewrapper

      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: cewrapper
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
